-- ============================================================
-- Mathe9
-- Freigabeliste, Tracking und langfristiger Lernfortschritt
--
-- Dieses Skript ist für eine erneute Ausführung vorbereitet.
-- Vorhandene Tabellen und Daten bleiben grundsätzlich erhalten.
--
-- Bei mehrfach vorhandenen Fortschrittszeilen für dieselbe
-- Kombination aus Schüler, Einheit und Lernpfad bleibt der
-- zuletzt aktualisierte Datensatz erhalten.
-- ============================================================

begin;


-- ============================================================
-- Erweiterungen
-- ============================================================

create extension if not exists pgcrypto;


-- ============================================================
-- Schüler-Freigabeliste
-- ============================================================

create table if not exists public.mathe9_students (
  id uuid
    primary key
    default gen_random_uuid(),

  login_name text
    not null,

  display_name text
    not null,

  class_code text
    not null,

  active boolean
    not null
    default true,

  created_at timestamptz
    not null
    default now(),

  updated_at timestamptz
    not null
    default now(),

  constraint mathe9_students_login_format
    check (
      login_name ~
      '^[^[:space:].]+\.[^[:space:].]+$'
    ),

  constraint mathe9_students_login_group_unique
    unique (
      login_name,
      class_code
    )
);


-- ============================================================
-- Einzelereignisse
-- ============================================================

create table if not exists public.mathe9_events (
  id bigint
    generated by default as identity
    primary key,

  event_type text
    not null,

  student_id uuid
    references public.mathe9_students(id)
    on delete set null,

  student text
    not null
    default 'anonym',

  device_id uuid
    not null,

  session_id uuid
    not null,

  class_code text,

  page text,

  unit text,

  path text,

  task text,

  payload jsonb
    not null
    default '{}'::jsonb,

  ts timestamptz
    not null
    default now()
);


-- ============================================================
-- Zusammengefasster Lernfortschritt
-- ============================================================

create table if not exists public.mathe9_progress (
  id bigint
    generated by default as identity
    primary key,

  student_id uuid
    references public.mathe9_students(id)
    on delete cascade,

  student text
    not null
    default 'anonym',

  device_id uuid
    not null,

  session_id uuid
    not null,

  class_code text,

  page text,

  unit text
    not null,

  path text
    not null
    default '',

  current_task text,

  completed_tasks integer
    not null
    default 0,

  total_tasks integer
    not null
    default 0,

  progress_percent integer
    not null
    default 0
    check (
      progress_percent
      between 0 and 100
    ),

  correct_count integer
    not null
    default 0,

  attempts_count integer
    not null
    default 0,

  status text
    not null
    default 'active',

  ts timestamptz
    not null
    default now(),

  updated_at timestamptz
    not null
    default now()
);


-- ============================================================
-- Migration bereits vorhandener Tabellen
-- ============================================================

alter table public.mathe9_events
  add column if not exists student_id uuid
  references public.mathe9_students(id)
  on delete set null;

alter table public.mathe9_progress
  add column if not exists student_id uuid
  references public.mathe9_students(id)
  on delete cascade;


-- Alte Eindeutigkeitsregeln entfernen, falls sie vorhanden sind.

alter table public.mathe9_progress
  drop constraint if exists
  mathe9_progress_device_id_session_id_unit_path_key;

alter table public.mathe9_progress
  drop constraint if exists
  mathe9_progress_device_unit_path_key;


-- ============================================================
-- Bestehende Werte normalisieren
--
-- Diese Anweisungen sind vor allem für ältere Tabellenstände
-- gedacht, in denen einzelne Felder noch NULL sein könnten.
-- ============================================================

update public.mathe9_progress
set
  path = coalesce(path, ''),
  completed_tasks = greatest(
    0,
    coalesce(completed_tasks, 0)
  ),
  total_tasks = greatest(
    0,
    coalesce(total_tasks, 0)
  ),
  progress_percent = least(
    100,
    greatest(
      0,
      coalesce(progress_percent, 0)
    )
  ),
  correct_count = greatest(
    0,
    coalesce(correct_count, 0)
  ),
  attempts_count = greatest(
    0,
    coalesce(attempts_count, 0)
  ),
  status = coalesce(
    nullif(trim(status), ''),
    'active'
  ),
  updated_at = coalesce(
    updated_at,
    ts,
    now()
  );


-- ============================================================
-- Vorhandene Fortschritts-Dubletten bereinigen
--
-- Eindeutig sein soll:
--
--   student_id + unit + path
--
-- Wenn dieselbe Kombination mehrfach vorkommt, bleibt:
--
--   1. der zuletzt aktualisierte Datensatz,
--   2. bei identischem Zeitpunkt der Datensatz mit der
--      höchsten ID.
--
-- Datensätze ohne student_id werden hier nicht verändert.
-- ============================================================

with ranked_progress as (
  select
    id,

    row_number() over (
      partition by
        student_id,
        unit,
        path

      order by
        updated_at desc nulls last,
        ts desc nulls last,
        id desc
    ) as duplicate_position

  from public.mathe9_progress

  where student_id is not null
)

delete from public.mathe9_progress as progress

using ranked_progress as ranked

where
  progress.id = ranked.id
  and ranked.duplicate_position > 1;


-- ============================================================
-- Eindeutiger Schlüssel für den Fortschritts-Upsert
--
-- Dieser Index entspricht exakt dem Tracker-Aufruf:
--
-- on_conflict=student_id,unit,path
-- ============================================================

drop index if exists
  public.mathe9_progress_student_unit_path_uidx;

create unique index
  mathe9_progress_student_unit_path_uidx

on public.mathe9_progress (
  student_id,
  unit,
  path
);


-- ============================================================
-- Zusätzliche Indizes
-- ============================================================

create index if not exists
  mathe9_events_ts_idx

on public.mathe9_events (
  ts desc
);


create index if not exists
  mathe9_events_student_idx

on public.mathe9_events (
  student_id,
  ts desc
);


create index if not exists
  mathe9_events_type_idx

on public.mathe9_events (
  event_type,
  ts desc
);


-- Aufgaben-Sitzung: Alle Ereignisse EINER Bearbeitung tragen dieselbe ID in
-- der Nutzlast. Damit lassen sich Versuche auch dann korrekt bündeln, wenn
-- offline nachgeliefert wird, mehrere Tabs offen sind oder dieselbe Aufgabe
-- ein zweites Mal bearbeitet wird.
create index if not exists
  mathe9_events_task_session_idx

on public.mathe9_events (
  (payload ->> 'task_session_id'),
  ts
);


create index if not exists
  mathe9_progress_updated_idx

on public.mathe9_progress (
  updated_at desc
);


create index if not exists
  mathe9_students_class_idx

on public.mathe9_students (
  class_code,
  active,
  login_name
);


-- ============================================================
-- Login-Prüfung ohne Offenlegung der Schülerliste
-- ============================================================

create or replace function
  public.mathe9_validate_student_login(
    p_login_name text,
    p_class_code text
  )

returns table (
  student_id uuid,
  login_name text,
  display_name text,
  class_code text
)

language sql

security definer

set search_path = public

stable

as $$

  select
    student.id,
    student.login_name,
    student.display_name,
    student.class_code

  from public.mathe9_students as student

  where
    lower(student.login_name) =
      lower(trim(p_login_name))

    and student.class_code =
      trim(p_class_code)

    and student.active = true

  limit 1;

$$;


-- ============================================================
-- Rechte der Login-Funktion
-- ============================================================

revoke all
on function
  public.mathe9_validate_student_login(
    text,
    text
  )
from public;


grant execute
on function
  public.mathe9_validate_student_login(
    text,
    text
  )
to anon, authenticated;


-- ============================================================
-- Row Level Security aktivieren
-- ============================================================

alter table
  public.mathe9_students
enable row level security;


alter table
  public.mathe9_events
enable row level security;


alter table
  public.mathe9_progress
enable row level security;


-- ============================================================
-- Bestehende Policies entfernen
--
-- Dadurch kann das Skript erneut ausgeführt werden.
-- ============================================================

drop policy if exists
  "teachers read students"
on public.mathe9_students;


drop policy if exists
  "teachers insert students"
on public.mathe9_students;


drop policy if exists
  "teachers update students"
on public.mathe9_students;


drop policy if exists
  "teachers delete students"
on public.mathe9_students;


drop policy if exists
  "students insert events"
on public.mathe9_events;


drop policy if exists
  "students insert progress"
on public.mathe9_progress;


drop policy if exists
  "students update progress"
on public.mathe9_progress;


drop policy if exists
  "teachers read events"
on public.mathe9_events;


drop policy if exists
  "teachers read progress"
on public.mathe9_progress;


-- ============================================================
-- Freigabeliste nur für angemeldete Lehrkräfte
-- ============================================================

create policy
  "teachers read students"

on public.mathe9_students

for select

to authenticated

using (true);


create policy
  "teachers insert students"

on public.mathe9_students

for insert

to authenticated

with check (true);


create policy
  "teachers update students"

on public.mathe9_students

for update

to authenticated

using (true)

with check (true);


create policy
  "teachers delete students"

on public.mathe9_students

for delete

to authenticated

using (true);


-- ============================================================
-- Schüler-App
--
-- Die anonyme Anwendung darf Trackingdaten schreiben,
-- jedoch nicht die Schülerliste lesen.
-- ============================================================

create policy
  "students insert events"

on public.mathe9_events

for insert

to anon

with check (
  student_id is not null
);


create policy
  "students insert progress"

on public.mathe9_progress

for insert

to anon

with check (
  student_id is not null
);


create policy
  "students update progress"

on public.mathe9_progress

for update

to anon

using (
  student_id is not null
)

with check (
  student_id is not null
);


-- ============================================================
-- Dashboarddaten nur nach Lehrkraft-Login
-- ============================================================

create policy
  "teachers read events"

on public.mathe9_events

for select

to authenticated

using (true);


create policy
  "teachers read progress"

on public.mathe9_progress

for select

to authenticated

using (true);


-- ============================================================
-- Grundrechte
-- ============================================================

grant usage
on schema public
to anon, authenticated;


grant execute
on function
  public.mathe9_validate_student_login(
    text,
    text
  )
to anon, authenticated;


grant insert
on public.mathe9_events
to anon;


grant insert, update
on public.mathe9_progress
to anon;


grant select, insert, update, delete
on public.mathe9_students
to authenticated;


grant select
on
  public.mathe9_events,
  public.mathe9_progress
to authenticated;


grant usage, select
on all sequences in schema public
to anon, authenticated;


-- ============================================================
-- Protokoll der Datenpflege
--
-- Ein Aufräumjob, den niemand beobachtet, ist ein Datenschutzversprechen
-- auf Verdacht. Jeder Lauf schreibt deshalb hierher: wann, wie lange, wie
-- viele Zeilen — und im Fehlerfall die Meldung. Die Tabelle enthält nur
-- Zählwerte, keine Personendaten.
-- ============================================================

create table if not exists public.mathe9_wartung_laeufe (
  id bigserial primary key,

  gestartet_at timestamptz not null default now(),
  beendet_at timestamptz,

  erfolg boolean not null default false,
  fehler text,

  ereignisse bigint not null default 0,
  fortschritt bigint not null default 0,
  tokens bigint not null default 0,

  ereignis_tage integer,
  fortschritt_tage integer,

  ausgeloest_von text
);

alter table public.mathe9_wartung_laeufe enable row level security;

create index if not exists
  mathe9_wartung_laeufe_zeit_idx
  on public.mathe9_wartung_laeufe (gestartet_at desc);

drop policy if exists "teachers read wartung" on public.mathe9_wartung_laeufe;


-- ============================================================
-- Aufbewahrung und Löschung
-- Siehe DATENSCHUTZ.md. Fristen hier zentral, damit sie nicht in
-- Kommentaren stehen, sondern tatsächlich wirken.
-- ============================================================

-- Rohereignisse: 90 Tage. Fortschritt: ein Schuljahr.
create or replace function public.mathe9_aufraeumen(
  ereignis_tage integer default 90,
  fortschritt_tage integer default 365
)
returns table (tabelle text, geloescht bigint)
language plpgsql
security definer
set search_path = public
as $$
declare
  n_ereignisse bigint;
  n_fortschritt bigint;
  n_token bigint;
  erlaubt boolean := false;
  lauf bigint;
begin
  -- SECURITY DEFINER umgeht RLS. Ein EXECUTE-Recht allein reicht daher
  -- nicht: angemeldete Aufrufer werden zusätzlich gegen die Lehrkraftliste
  -- bzw. den serverseitigen teacher-Claim geprüft. pg_cron/SQL-Administration
  -- läuft ohne auth.uid() und darf die Wartung weiterhin ausführen.
  if auth.role() = 'authenticated' or auth.uid() is not null then
    execute $q$
      select exists (
        select 1 from public.mathe9_teachers t where t.user_id = $1
      ) or coalesce((auth.jwt() -> 'app_metadata' ->> 'role') = 'teacher', false)
    $q$ into erlaubt using auth.uid();
    if not erlaubt then
      raise exception 'Nur freigeschaltete Lehrkräfte dürfen die Datenbereinigung ausführen.'
        using errcode = '42501';
    end if;
  end if;

  -- Erst den Lauf eröffnen, dann arbeiten: Bricht der Job ab, bleibt eine
  -- Zeile mit erfolg = false stehen. Ein stiller Ausfall wäre sonst von
  -- „läuft, findet aber nichts" nicht zu unterscheiden.
  insert into public.mathe9_wartung_laeufe (ereignis_tage, fortschritt_tage, ausgeloest_von)
  values (
    ereignis_tage,
    fortschritt_tage,
    coalesce(nullif(auth.uid()::text, ''), 'planmaessig')
  )
  returning id into lauf;

  begin
    delete from public.mathe9_events
    where ts < now() - make_interval(days => ereignis_tage);
    get diagnostics n_ereignisse = row_count;

    delete from public.mathe9_progress
    where coalesce(updated_at, ts) < now() - make_interval(days => fortschritt_tage);
    get diagnostics n_fortschritt = row_count;

    -- Abgelaufene Sitzungstoken enthalten keine Lernantworten, sollten aber
    -- ebenfalls nicht unbegrenzt anwachsen.
    begin
      delete from public.mathe9_student_tokens where gueltig_bis < now();
      get diagnostics n_token = row_count;
    exception when undefined_table then
      n_token := 0; -- erster Durchlauf einer älteren Installation
    end;

    -- Lernzeiten sind personenbezogen und unterliegen derselben Frist wie
    -- der Fortschritt. Freigaben bleiben an den Schülerdatensatz gebunden
    -- und verschwinden mit ihm (ON DELETE CASCADE).
    begin
      delete from public.mathe9_lernzeit
      where datum < (now() - make_interval(days => fortschritt_tage))::date;
    exception when undefined_table then
      null; -- ältere Installation ohne Lernzeittabelle
    end;

    -- Quizergebnisse sind Bewertungsgrundlage und unterliegen derselben
    -- Frist. Sie ohne Frist stehen zu lassen, wäre die einzige
    -- personenbezogene Sammlung im Projekt, die nie endet.
    begin
      delete from public.mathe9_quiz_ergebnisse
      where datum < (now() - make_interval(days => fortschritt_tage))::date;
    exception when undefined_table then
      null; -- ältere Installation ohne Quiztabelle
    end;
  exception when others then
    update public.mathe9_wartung_laeufe
       set beendet_at = now(), erfolg = false, fehler = left(sqlerrm, 500)
     where id = lauf;
    raise;
  end;

  update public.mathe9_wartung_laeufe
     set beendet_at = now(),
         erfolg = true,
         ereignisse = n_ereignisse,
         fortschritt = n_fortschritt,
         tokens = n_token
   where id = lauf;

  -- Das Protokoll selbst darf ebenfalls nicht unbegrenzt wachsen.
  delete from public.mathe9_wartung_laeufe
  where gestartet_at < now() - interval '400 days';

  return query
    select 'mathe9_events'::text, n_ereignisse
    union all
    select 'mathe9_progress'::text, n_fortschritt
    union all
    select 'mathe9_student_tokens'::text, n_token;
end;
$$;

comment on function public.mathe9_aufraeumen is
  'Löscht abgelaufene Ereignisse, Fortschrittssätze und Sitzungstoken. Muss planmäßig '
  'aufgerufen werden (pg_cron oder wöchentlich von Hand) — ohne Aufruf '
  'passiert nichts. Jeder Lauf wird in mathe9_wartung_laeufe protokolliert.';


-- Zustand der Datenpflege für das Dashboard. Bewusst eine Funktion und
-- keine Tabellenabfrage: Die Bewertung „überfällig" gehört an eine Stelle,
-- nicht in jeden Client.
create or replace function public.mathe9_wartung_status()
returns table (
  letzter_lauf timestamptz,
  letzter_erfolg timestamptz,
  erfolg boolean,
  fehler text,
  ereignisse bigint,
  fortschritt bigint,
  tokens bigint,
  tage_seit_erfolg numeric,
  ueberfaellig boolean,
  laeufe_30_tage bigint
)
language plpgsql
stable
security definer
set search_path = public
as $fn$
declare
  letzter public.mathe9_wartung_laeufe%rowtype;
  erfolgreich timestamptz;
begin
  if not public.mathe9_ist_lehrkraft() then
    raise exception 'Nur freigeschaltete Lehrkräfte dürfen den Wartungsstatus lesen.'
      using errcode = '42501';
  end if;

  select * into letzter from public.mathe9_wartung_laeufe
   order by gestartet_at desc limit 1;

  select max(w.gestartet_at) into erfolgreich
    from public.mathe9_wartung_laeufe w where w.erfolg;

  -- Immer genau eine Zeile: „noch nie gelaufen" ist selbst ein Befund und
  -- soll im Dashboard sichtbar werden, nicht als leere Antwort verschwinden.
  return query select
    letzter.gestartet_at,
    erfolgreich,
    coalesce(letzter.erfolg, false),
    letzter.fehler,
    coalesce(letzter.ereignisse, 0::bigint),
    coalesce(letzter.fortschritt, 0::bigint),
    coalesce(letzter.tokens, 0::bigint),
    round(extract(epoch from now() - erfolgreich) / 86400.0, 1),
    -- Geplant ist ein wöchentlicher Lauf. Nach zehn Tagen ohne Erfolg ist
    -- etwas kaputt: pg_cron abgeschaltet, Fehler im Job, Projekt pausiert.
    coalesce(erfolgreich < now() - interval '10 days', true),
    (select count(*) from public.mathe9_wartung_laeufe w2
      where w2.gestartet_at > now() - interval '30 days');
end;
$fn$;

revoke all on function public.mathe9_wartung_status() from public, anon;
grant execute on function public.mathe9_wartung_status() to authenticated;


-- Auskunftsrecht: alles zu einer Person an einer Stelle.
create or replace function public.mathe9_person_export(kennung uuid)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  erlaubt boolean := false;
  ergebnis jsonb;
begin
  if auth.role() = 'authenticated' or auth.uid() is not null then
    execute $q$
      select exists (
        select 1 from public.mathe9_teachers t where t.user_id = $1
      ) or coalesce((auth.jwt() -> 'app_metadata' ->> 'role') = 'teacher', false)
    $q$ into erlaubt using auth.uid();
    if not erlaubt then
      raise exception 'Nur freigeschaltete Lehrkräfte dürfen Personendaten exportieren.'
        using errcode = '42501';
    end if;
  end if;

  select jsonb_build_object(
    'schueler',    (select to_jsonb(st) from public.mathe9_students st where st.id = kennung),
    'ereignisse',  (select coalesce(jsonb_agg(to_jsonb(e) order by e.ts), '[]'::jsonb)
                      from public.mathe9_events e where e.student_id = kennung),
    'fortschritt', (select coalesce(jsonb_agg(to_jsonb(pr)), '[]'::jsonb)
                      from public.mathe9_progress pr where pr.student_id = kennung),
    -- Auch Freigaben und Lernzeiten sind personenbezogen und gehoeren in
    -- eine Auskunft. Ein Export, der die Haelfte weglaesst, ist keiner.
    'freigaben',   (select coalesce(jsonb_agg(to_jsonb(fr) order by fr.freigegeben_at), '[]'::jsonb)
                      from public.mathe9_freigaben fr where fr.student_id = kennung),
    'lernzeit',    (select coalesce(jsonb_agg(to_jsonb(lz) order by lz.datum), '[]'::jsonb)
                      from public.mathe9_lernzeit lz where lz.student_id = kennung),
    -- Die Quizergebnisse begründen eine Note. Gerade sie gehören in eine
    -- Auskunft: Wer wissen will, worauf seine Bewertung beruht, findet es
    -- sonst nirgends.
    'quiz',        (select coalesce(jsonb_agg(to_jsonb(qz) order by qz.datum, qz.id), '[]'::jsonb)
                      from public.mathe9_quiz_ergebnisse qz where qz.student_id = kennung)
  ) into ergebnis;
  return ergebnis;
end;
$$;


-- Löschrecht: Ereignisse, Fortschritt und Freigabeeintrag einer Person.
create or replace function public.mathe9_person_loeschen(kennung uuid)
returns table (tabelle text, geloescht bigint)
language plpgsql
security definer
set search_path = public
as $$
declare
  n_ereignisse bigint;
  n_fortschritt bigint;
  n_quiz bigint;
  n_schueler bigint;
  erlaubt boolean := false;
begin
  if auth.role() = 'authenticated' or auth.uid() is not null then
    execute $q$
      select exists (
        select 1 from public.mathe9_teachers t where t.user_id = $1
      ) or coalesce((auth.jwt() -> 'app_metadata' ->> 'role') = 'teacher', false)
    $q$ into erlaubt using auth.uid();
    if not erlaubt then
      raise exception 'Nur freigeschaltete Lehrkräfte dürfen Personendaten löschen.'
        using errcode = '42501';
    end if;
  end if;
  delete from public.mathe9_events where student_id = kennung;
  get diagnostics n_ereignisse = row_count;

  delete from public.mathe9_progress where student_id = kennung;
  get diagnostics n_fortschritt = row_count;

  -- Der Fremdschluessel loescht die Quizergebnisse ohnehin mit dem
  -- Schuelersatz. Hier stehen sie trotzdem einzeln: Eine Loeschauskunft,
  -- die die Bewertungsgrundlage nicht nennt, beantwortet die Frage nicht,
  -- die gestellt wurde.
  begin
    delete from public.mathe9_quiz_ergebnisse where student_id = kennung;
    get diagnostics n_quiz = row_count;
  exception when undefined_table then
    n_quiz := 0; -- aeltere Installation ohne Quiztabelle
  end;

  delete from public.mathe9_students where id = kennung;
  get diagnostics n_schueler = row_count;

  return query
    select 'mathe9_events'::text, n_ereignisse
    union all
    select 'mathe9_progress'::text, n_fortschritt
    union all
    select 'mathe9_quiz_ergebnisse'::text, n_quiz
    union all
    select 'mathe9_students'::text, n_schueler;
end;
$$;

-- Diese drei Funktionen sind Verwaltungswerkzeuge und gehören NICHT in die
-- Hand der Anwendung. Nur angemeldete Lehrkräfte dürfen sie aufrufen.
revoke all on function public.mathe9_aufraeumen(integer, integer) from public, anon;
revoke all on function public.mathe9_person_export(uuid) from public, anon;
revoke all on function public.mathe9_person_loeschen(uuid) from public, anon;

grant execute on function public.mathe9_aufraeumen(integer, integer) to authenticated;
grant execute on function public.mathe9_person_export(uuid) to authenticated;
grant execute on function public.mathe9_person_loeschen(uuid) to authenticated;


-- ============================================================
-- Lehrkraft-Freigabe
--
-- Vorher galt JEDER Supabase-Nutzer mit der Rolle "authenticated" als
-- Lehrkraft. Wer sich irgendwo im Projekt ein Konto anlegen konnte, sah
-- damit alle Lernenden. Jetzt entscheidet eine Freigabeliste.
--
-- ACHTUNG BEIM ERSTEN LAUF: Solange die Liste leer ist, sieht niemand
-- Dashboarddaten. Das ist Absicht — der sichere Zustand ist der leere.
-- Einmalig freischalten:
--
--   select public.mathe9_lehrkraft_freischalten('lehrerin@schule.de');
--
-- ============================================================

create table if not exists public.mathe9_teachers (
  user_id uuid
    primary key
    references auth.users(id)
    on delete cascade,

  email text,

  display_name text,

  created_at timestamptz
    not null
    default now()
);

alter table public.mathe9_teachers enable row level security;


-- ------------------------------------------------------------
-- Protokoll der Lehrkraftfreigaben
--
-- Wer sieht die Daten aller Lernenden — und seit wann, auf wessen
-- Veranlassung? Ohne Protokoll ist das nach einem halben Jahr nicht mehr
-- zu beantworten. Die Tabelle hält jede Änderung fest; gelöscht wird hier
-- nichts, auch nicht beim Entzug der Freigabe.
-- ------------------------------------------------------------

create table if not exists public.mathe9_teacher_audit (
  id bigserial primary key,

  zeit timestamptz not null default now(),

  -- 'freigeschaltet' | 'gesperrt'
  aktion text not null,

  ziel_user_id uuid,
  ziel_email text,

  -- NULL bedeutet: direkt über die Datenbankverwaltung, ohne Benutzer-JWT.
  ausgefuehrt_von uuid,
  ausgefuehrt_von_email text,

  hinweis text
);

alter table public.mathe9_teacher_audit enable row level security;

create index if not exists
  mathe9_teacher_audit_zeit_idx
  on public.mathe9_teacher_audit (zeit desc);


-- Freigabe erteilen. Wird von der Datenbankverwaltung aufgerufen,
-- nicht von der Anwendung.
--
-- Die frühere einstellige Fassung muss weichen: Sie wäre neben der neuen
-- Signatur mit Vorgabewert nicht mehr eindeutig aufrufbar.
drop function if exists public.mathe9_lehrkraft_freischalten(text);

create or replace function public.mathe9_lehrkraft_freischalten(
  p_email text,
  p_hinweis text default null
)
returns uuid
language plpgsql
security definer
set search_path = public
as $fn$
declare
  ziel uuid;
  neu integer;
begin
  select id into ziel from auth.users where lower(email) = lower(p_email) limit 1;
  if ziel is null then
    raise exception 'Kein Supabase-Konto mit der Adresse % gefunden. Erst Konto anlegen, dann freischalten.', p_email;
  end if;

  insert into public.mathe9_teachers (user_id, email)
  values (ziel, lower(p_email))
  on conflict (user_id) do nothing;

  get diagnostics neu = row_count;

  -- Nur echte Änderungen protokollieren. Ein zweiter Aufruf mit derselben
  -- Adresse ist ein Versehen, kein Vorgang.
  if neu > 0 then
    insert into public.mathe9_teacher_audit
      (aktion, ziel_user_id, ziel_email, ausgefuehrt_von, ausgefuehrt_von_email, hinweis)
    values (
      'freigeschaltet', ziel, lower(p_email), auth.uid(),
      (select u.email from auth.users u where u.id = auth.uid()),
      p_hinweis
    );
  end if;

  return ziel;
end;
$fn$;

revoke all on function public.mathe9_lehrkraft_freischalten(text, text) from public, anon, authenticated;


-- Freigabe entziehen. Das Gegenstück, das bisher fehlte: Ohne eigene
-- Funktion wurde von Hand in mathe9_teachers gelöscht — spurlos.
create or replace function public.mathe9_lehrkraft_sperren(
  p_email text,
  p_hinweis text default null
)
returns boolean
language plpgsql
security definer
set search_path = public
as $fn$
declare
  ziel uuid;
  entfernt integer;
begin
  select user_id into ziel from public.mathe9_teachers
   where lower(email) = lower(p_email) limit 1;

  if ziel is null then
    select id into ziel from auth.users where lower(email) = lower(p_email) limit 1;
  end if;

  delete from public.mathe9_teachers where user_id = ziel;
  get diagnostics entfernt = row_count;

  if entfernt > 0 then
    insert into public.mathe9_teacher_audit
      (aktion, ziel_user_id, ziel_email, ausgefuehrt_von, ausgefuehrt_von_email, hinweis)
    values (
      'gesperrt', ziel, lower(p_email), auth.uid(),
      (select u.email from auth.users u where u.id = auth.uid()),
      p_hinweis
    );
  end if;

  return entfernt > 0;
end;
$fn$;

revoke all on function public.mathe9_lehrkraft_sperren(text, text) from public, anon, authenticated;


-- Die Prüfung, die alle Lehrkraft-Policies verwenden. Zusätzlich zur
-- Freigabeliste zählt ein serverseitig gesetzter Claim role = teacher —
-- damit lässt sich die Rolle auch zentral über die Nutzerverwaltung setzen.
create or replace function public.mathe9_ist_lehrkraft()
returns boolean
language sql
stable
security definer
set search_path = public
as $fn$
  select
    exists (
      select 1
      from public.mathe9_teachers t
      where t.user_id = auth.uid()
    )
    or coalesce(
      (auth.jwt() -> 'app_metadata' ->> 'role') = 'teacher',
      false
    );
$fn$;

grant execute on function public.mathe9_ist_lehrkraft() to authenticated;


-- Lehrkräfte sehen ihre eigene Freigabe, sonst niemand.
drop policy if exists "teachers read own membership" on public.mathe9_teachers;

create policy
  "teachers read own membership"

on public.mathe9_teachers

for select

to authenticated

using (user_id = auth.uid());


-- Protokolle sind für freigeschaltete Lehrkräfte lesbar — und nur lesbar.
-- Geschrieben wird ausschließlich aus SECURITY-DEFINER-Funktionen.
drop policy if exists "teachers read audit" on public.mathe9_teacher_audit;

create policy "teachers read audit"
on public.mathe9_teacher_audit
for select
to authenticated
using (public.mathe9_ist_lehrkraft());

create policy "teachers read wartung"
on public.mathe9_wartung_laeufe
for select
to authenticated
using (public.mathe9_ist_lehrkraft());

grant select on public.mathe9_teacher_audit to authenticated;
grant select on public.mathe9_wartung_laeufe to authenticated;


-- Regelmäßige Kontrolle alter Lehrerkonten: Wer ist freigeschaltet, seit
-- wann, und wann war er zuletzt angemeldet? Ein Konto, das seit Monaten
-- niemand benutzt, gehört überprüft — nicht stillschweigend behalten.
create or replace function public.mathe9_lehrkraft_uebersicht()
returns table (
  email text,
  freigeschaltet_am timestamptz,
  zuletzt_angemeldet timestamptz,
  tage_ohne_anmeldung numeric,
  pruefen boolean
)
language plpgsql
stable
security definer
set search_path = public
as $fn$
begin
  if not public.mathe9_ist_lehrkraft() then
    raise exception 'Nur freigeschaltete Lehrkräfte dürfen die Lehrkraftliste einsehen.'
      using errcode = '42501';
  end if;

  return query
    select
      coalesce(t.email, u.email)::text,
      t.created_at,
      u.last_sign_in_at,
      round(extract(epoch from now() - u.last_sign_in_at) / 86400.0, 1),
      coalesce(u.last_sign_in_at < now() - interval '180 days', true)
    from public.mathe9_teachers t
    left join auth.users u on u.id = t.user_id
    order by u.last_sign_in_at asc nulls first;
end;
$fn$;

revoke all on function public.mathe9_lehrkraft_uebersicht() from public, anon;
grant execute on function public.mathe9_lehrkraft_uebersicht() to authenticated;


-- ============================================================
-- Schreibrecht der Schüler-App kryptografisch binden
--
-- Vorher genügte eine beliebige nichtleere student_id: Wer den anon-Key
-- kannte, konnte Daten im Namen jedes Kindes schreiben. Jetzt stellt die
-- Anmeldung ein kurzlebiges Token aus. Gespeichert wird nur sein Hash;
-- gesendet wird es als Kopfzeile x-mathe9-token.
-- ============================================================

create table if not exists public.mathe9_student_tokens (
  token_hash text
    primary key,

  student_id uuid
    not null
    references public.mathe9_students(id)
    on delete cascade,

  ausgestellt timestamptz
    not null
    default now(),

  gueltig_bis timestamptz
    not null
);

alter table public.mathe9_student_tokens enable row level security;
-- Bewusst ohne Policy: Auf die Tabelle greift ausschliesslich
-- SECURITY-DEFINER-Code zu, niemand sonst.

create index if not exists
  mathe9_student_tokens_gueltig_idx
on public.mathe9_student_tokens (gueltig_bis);


-- Anmeldung mit Tokenausgabe. Ersetzt mathe9_validate_student_login;
-- die alte Funktion bleibt fuer aeltere Clients bestehen.
create or replace function public.mathe9_student_anmelden(
  p_login_name text,
  p_class_code text,
  p_stunden integer default 12
)
returns table (
  student_id uuid,
  login_name text,
  display_name text,
  class_code text,
  token text,
  gueltig_bis timestamptz
)
language plpgsql
security definer
set search_path = public
as $fn$
declare
  gefunden record;
  neues_token text;
  frist timestamptz;
begin
  select st.id, st.login_name, st.display_name, st.class_code
    into gefunden
  from public.mathe9_students as st
  where lower(st.login_name) = lower(trim(p_login_name))
    and lower(st.class_code) = lower(trim(p_class_code))
    and st.active
  limit 1;

  if gefunden.id is null then
    return;                      -- keine Zeile: Anmeldung abgelehnt
  end if;

  -- Ein Schultag plus Puffer. Laenger als noetig waere ein unnoetiges
  -- Risiko auf einem Geraet, das die naechste Klasse benutzt.
  frist := now() + make_interval(hours => greatest(1, least(24, coalesce(p_stunden, 12))));
  neues_token := encode(gen_random_bytes(32), 'hex');

  insert into public.mathe9_student_tokens (token_hash, student_id, gueltig_bis)
  values (encode(digest(neues_token, 'sha256'), 'hex'), gefunden.id, frist);

  -- Abgelaufene Token bei Gelegenheit entfernen.
  delete from public.mathe9_student_tokens where gueltig_bis < now() - interval '7 days';

  return query
    select gefunden.id, gefunden.login_name, gefunden.display_name,
           gefunden.class_code, neues_token, frist;
end;
$fn$;

revoke all on function public.mathe9_student_anmelden(text, text, integer) from public;
grant execute on function public.mathe9_student_anmelden(text, text, integer) to anon, authenticated;

-- Die alte Prüfung gab bei passenden Anmeldedaten eine Schüler-ID ohne
-- Sitzungstoken zurück. Neue Clients verwenden sie nicht mehr; ihr EXECUTE-
-- Recht wird nach der Migration entzogen, damit es keinen unsicheren
-- Parallelpfad gibt.
revoke all on function public.mathe9_validate_student_login(text, text)
  from public, anon, authenticated;


-- Welches Kind gehoert zum mitgesendeten Token? NULL heisst: kein gueltiges.
create or replace function public.mathe9_token_student()
returns uuid
language sql
stable
security definer
set search_path = public
as $fn$
  select t.student_id
  from public.mathe9_student_tokens t
  join public.mathe9_students st on st.id = t.student_id and st.active
  where t.token_hash = encode(
          digest(
            coalesce(
              nullif(current_setting('request.headers', true), '')::json ->> 'x-mathe9-token',
              ''
            ),
            'sha256'
          ),
          'hex'
        )
    and t.gueltig_bis > now()
  limit 1;
$fn$;

grant execute on function public.mathe9_token_student() to anon, authenticated;


-- Vorhandenes Token prüfen, ohne bei jedem Seitenwechsel ein neues
-- auszustellen. Die App kann so eine laufende Sitzung wiederverwenden.
create or replace function public.mathe9_student_sitzung()
returns table (
  student_id uuid,
  login_name text,
  display_name text,
  class_code text,
  gueltig_bis timestamptz
)
language sql
stable
security definer
set search_path = public
as $fn$
  select st.id, st.login_name, st.display_name, st.class_code, tok.gueltig_bis
  from public.mathe9_student_tokens tok
  join public.mathe9_students st on st.id = tok.student_id
  where tok.token_hash = encode(
          digest(
            coalesce(
              nullif(current_setting('request.headers', true), '')::json ->> 'x-mathe9-token',
              ''
            ),
            'sha256'
          ),
          'hex'
        )
    and tok.gueltig_bis > now()
    and st.active
  limit 1;
$fn$;

revoke all on function public.mathe9_student_sitzung() from public;
grant execute on function public.mathe9_student_sitzung() to anon, authenticated;


-- Abmelden: Token sofort entwerten.
create or replace function public.mathe9_student_abmelden()
returns integer
language plpgsql
security definer
set search_path = public
as $fn$
declare
  n integer;
begin
  delete from public.mathe9_student_tokens
  where token_hash = encode(
          digest(
            coalesce(
              nullif(current_setting('request.headers', true), '')::json ->> 'x-mathe9-token',
              ''
            ),
            'sha256'
          ),
          'hex'
        );
  get diagnostics n = row_count;
  return n;
end;
$fn$;

grant execute on function public.mathe9_student_abmelden() to anon, authenticated;


-- ============================================================
-- Policies neu fassen
-- ============================================================

drop policy if exists "teachers read students" on public.mathe9_students;
drop policy if exists "teachers insert students" on public.mathe9_students;
drop policy if exists "teachers update students" on public.mathe9_students;
drop policy if exists "teachers delete students" on public.mathe9_students;
drop policy if exists "teachers read events" on public.mathe9_events;
drop policy if exists "teachers read progress" on public.mathe9_progress;
drop policy if exists "students insert events" on public.mathe9_events;
drop policy if exists "students insert progress" on public.mathe9_progress;
drop policy if exists "students update progress" on public.mathe9_progress;

create policy "teachers read students" on public.mathe9_students
  for select to authenticated using (public.mathe9_ist_lehrkraft());

create policy "teachers insert students" on public.mathe9_students
  for insert to authenticated with check (public.mathe9_ist_lehrkraft());

create policy "teachers update students" on public.mathe9_students
  for update to authenticated using (public.mathe9_ist_lehrkraft())
  with check (public.mathe9_ist_lehrkraft());

create policy "teachers delete students" on public.mathe9_students
  for delete to authenticated using (public.mathe9_ist_lehrkraft());

create policy "teachers read events" on public.mathe9_events
  for select to authenticated using (public.mathe9_ist_lehrkraft());

create policy "teachers read progress" on public.mathe9_progress
  for select to authenticated using (public.mathe9_ist_lehrkraft());

-- Die Anwendung darf nur fuer DAS Kind schreiben, dessen Token sie mitsendet.
create policy "students insert events" on public.mathe9_events
  for insert to anon
  with check (student_id is not null and student_id = public.mathe9_token_student());

create policy "students insert progress" on public.mathe9_progress
  for insert to anon
  with check (student_id is not null and student_id = public.mathe9_token_student());

create policy "students update progress" on public.mathe9_progress
  for update to anon
  using (student_id is not null and student_id = public.mathe9_token_student())
  with check (student_id is not null and student_id = public.mathe9_token_student());


-- ============================================================
-- Lernmodus, Freigaben und aktive Lernzeit  (V30)
--
-- Zwei Betriebsarten:
--
--   Übungsmodus   — ausserhalb der Unterrichtszeit. Die Lernenden waehlen
--                   ihre Einheiten frei. Nichts ist gesperrt.
--   Bewertungsmodus — waehrend des Unterrichts. Eine neue Einheit oeffnet
--                   sich erst, wenn die Lehrkraft sie freigegeben hat —
--                   nach Sichtung des handschriftlichen Uebungsblattes.
--
-- Der Modus steht bewusst in der Datenbank und nicht im Browser: Eine
-- Sperre, die das Geraet selbst setzt, ist keine.
-- ============================================================

create table if not exists public.mathe9_unterricht (
  id smallint primary key default 1,
  modus text not null default 'uebung',
  -- Bis wann gilt der Bewertungsmodus? Danach faellt die Anwendung von
  -- selbst in den Uebungsmodus zurueck. Ohne dieses Ablaufdatum bliebe
  -- nach einer vergessenen Umschaltung die ganze Klasse gesperrt.
  gilt_bis timestamptz,
  klasse text,
  gesetzt_von uuid,
  gesetzt_at timestamptz not null default now(),
  constraint mathe9_unterricht_einzeln check (id = 1),
  constraint mathe9_unterricht_modus check (modus in ('uebung', 'bewertung'))
);

insert into public.mathe9_unterricht (id, modus)
values (1, 'uebung')
on conflict (id) do nothing;

alter table public.mathe9_unterricht enable row level security;


-- Eine Zeile je freigegebener Einheit und Person. Die Lehrkraft prueft nur,
-- OB handschriftlich gearbeitet wurde — nicht, ob richtig gerechnet wurde.
-- Das ist Absicht: Die Richtigkeit klaert der Selbstkontrollkasten auf dem
-- Blatt, die Freigabe klaert, dass ueberhaupt mit der Hand gerechnet wurde.
create table if not exists public.mathe9_freigaben (
  student_id uuid not null references public.mathe9_students(id) on delete cascade,
  unit text not null,
  freigegeben_at timestamptz not null default now(),
  freigegeben_von uuid,
  handschrift_gesehen boolean not null default true,
  hinweis text,
  primary key (student_id, unit)
);

alter table public.mathe9_freigaben enable row level security;

create index if not exists
  mathe9_freigaben_zeit_idx
  on public.mathe9_freigaben (freigegeben_at desc);


-- Aktive Lernzeit, tageweise und je Einheit summiert.
--
-- Gezaehlt werden nur Sekunden, in denen die Seite sichtbar war UND es
-- kurz zuvor eine Aktivitaet gab UND der Ping tatsaechlich ankam. Die
-- Anwendung sammelt lokal und meldet Zuwaechse; angerechnet wird also nur,
-- was den Server erreicht hat.
create table if not exists public.mathe9_lernzeit (
  student_id uuid not null references public.mathe9_students(id) on delete cascade,
  datum date not null default (now() at time zone 'Europe/Berlin')::date,
  unit text not null default '—',
  sekunden integer not null default 0,
  aktualisiert_at timestamptz not null default now(),
  primary key (student_id, datum, unit)
);

alter table public.mathe9_lernzeit enable row level security;

create index if not exists
  mathe9_lernzeit_datum_idx
  on public.mathe9_lernzeit (datum desc);


-- ------------------------------------------------------------
-- Was darf dieses Kind gerade?  (Aufruf mit Schueler-Token)
-- ------------------------------------------------------------
create or replace function public.mathe9_lernmodus()
returns table (
  modus text,
  gilt_bis timestamptz,
  freigegeben text[],
  lernzeit_heute integer
)
language plpgsql
stable
security definer
set search_path = public
as $fn$
declare
  kind uuid;
  aktuell public.mathe9_unterricht%rowtype;
begin
  kind := public.mathe9_token_student();
  if kind is null then
    raise exception 'Kein gueltiges Schueler-Sitzungstoken.' using errcode = '42501';
  end if;

  select * into aktuell from public.mathe9_unterricht where id = 1;

  return query select
    -- Abgelaufener Bewertungsmodus gilt nicht mehr. Der Rueckfall ist der
    -- offene Zustand, nicht der gesperrte: Eine vergessene Umschaltung darf
    -- niemanden aussperren.
    case
      when aktuell.modus = 'bewertung'
       and (aktuell.gilt_bis is null or aktuell.gilt_bis > now())
      then 'bewertung'
      else 'uebung'
    end::text,
    aktuell.gilt_bis,
    coalesce((
      select array_agg(f.unit order by f.unit)
      from public.mathe9_freigaben f
      where f.student_id = kind
    ), array[]::text[]),
    coalesce((
      select sum(l.sekunden)::integer
      from public.mathe9_lernzeit l
      where l.student_id = kind
        and l.datum = (now() at time zone 'Europe/Berlin')::date
    ), 0);
end;
$fn$;

revoke all on function public.mathe9_lernmodus() from public;
grant execute on function public.mathe9_lernmodus() to anon, authenticated;


-- ------------------------------------------------------------
-- Aktive Lernzeit melden  (Aufruf mit Schueler-Token)
-- ------------------------------------------------------------
create or replace function public.mathe9_lernzeit_melden(
  p_unit text,
  p_sekunden integer
)
returns integer
language plpgsql
security definer
set search_path = public
as $fn$
declare
  kind uuid;
  zuwachs integer;
begin
  kind := public.mathe9_token_student();
  if kind is null then
    raise exception 'Kein gueltiges Schueler-Sitzungstoken.' using errcode = '42501';
  end if;

  -- Obergrenze je Meldung: Die App meldet alle paar Minuten. Ein groesserer
  -- Wert kaeme entweder von einer sehr langen Offlinephase oder von einem
  -- manipulierten Aufruf. In beiden Faellen ist Deckeln richtiger als
  -- Glauben.
  zuwachs := least(greatest(coalesce(p_sekunden, 0), 0), 900);
  if zuwachs = 0 then
    return 0;
  end if;

  insert into public.mathe9_lernzeit (student_id, unit, sekunden)
  values (kind, coalesce(nullif(trim(p_unit), ''), '—'), zuwachs)
  on conflict (student_id, datum, unit) do update
    set sekunden = public.mathe9_lernzeit.sekunden + excluded.sekunden,
        aktualisiert_at = now();

  return zuwachs;
end;
$fn$;

revoke all on function public.mathe9_lernzeit_melden(text, integer) from public;
grant execute on function public.mathe9_lernzeit_melden(text, integer) to anon, authenticated;


-- ------------------------------------------------------------
-- Lehrkraftseite: Modus umschalten und Einheiten freigeben
-- ------------------------------------------------------------
create or replace function public.mathe9_unterricht_setzen(
  p_modus text,
  p_minuten integer default 90,
  p_klasse text default null
)
returns public.mathe9_unterricht
language plpgsql
security definer
set search_path = public
as $fn$
declare
  ergebnis public.mathe9_unterricht%rowtype;
begin
  if not public.mathe9_ist_lehrkraft() then
    raise exception 'Nur freigeschaltete Lehrkraefte duerfen den Lernmodus umschalten.'
      using errcode = '42501';
  end if;
  if p_modus not in ('uebung', 'bewertung') then
    raise exception 'Unbekannter Modus: %', p_modus;
  end if;

  update public.mathe9_unterricht
     set modus = p_modus,
         gilt_bis = case
           when p_modus = 'bewertung'
           then now() + make_interval(mins => greatest(coalesce(p_minuten, 90), 5))
           else null
         end,
         klasse = p_klasse,
         gesetzt_von = auth.uid(),
         gesetzt_at = now()
   where id = 1
  returning * into ergebnis;

  return ergebnis;
end;
$fn$;

revoke all on function public.mathe9_unterricht_setzen(text, integer, text) from public, anon;
grant execute on function public.mathe9_unterricht_setzen(text, integer, text) to authenticated;


-- Freigabe nach Sichtung des handschriftlichen Blattes.
create or replace function public.mathe9_freigeben(
  p_student uuid,
  p_unit text,
  p_hinweis text default null
)
returns boolean
language plpgsql
security definer
set search_path = public
as $fn$
begin
  if not public.mathe9_ist_lehrkraft() then
    raise exception 'Nur freigeschaltete Lehrkraefte duerfen Einheiten freigeben.'
      using errcode = '42501';
  end if;
  if p_unit is null or trim(p_unit) = '' then
    raise exception 'Ohne Einheit keine Freigabe.';
  end if;

  insert into public.mathe9_freigaben (student_id, unit, freigegeben_von, hinweis)
  values (p_student, lower(trim(p_unit)), auth.uid(), p_hinweis)
  on conflict (student_id, unit) do update
    set freigegeben_at = now(),
        freigegeben_von = auth.uid(),
        hinweis = coalesce(excluded.hinweis, public.mathe9_freigaben.hinweis);

  return true;
end;
$fn$;

revoke all on function public.mathe9_freigeben(uuid, text, text) from public, anon;
grant execute on function public.mathe9_freigeben(uuid, text, text) to authenticated;


create or replace function public.mathe9_freigabe_zuruecknehmen(
  p_student uuid,
  p_unit text
)
returns boolean
language plpgsql
security definer
set search_path = public
as $fn$
declare
  entfernt integer;
begin
  if not public.mathe9_ist_lehrkraft() then
    raise exception 'Nur freigeschaltete Lehrkraefte duerfen Freigaben zuruecknehmen.'
      using errcode = '42501';
  end if;

  delete from public.mathe9_freigaben
   where student_id = p_student and unit = lower(trim(p_unit));
  get diagnostics entfernt = row_count;
  return entfernt > 0;
end;
$fn$;

revoke all on function public.mathe9_freigabe_zuruecknehmen(uuid, text) from public, anon;
grant execute on function public.mathe9_freigabe_zuruecknehmen(uuid, text) to authenticated;


-- Policies: Lehrkraefte lesen alles, geschrieben wird nur ueber die
-- Funktionen oben. Die Schueler-App liest ihren Modus ausschliesslich
-- ueber mathe9_lernmodus() — direkten Tabellenzugriff bekommt sie nicht,
-- sonst waere die Freigabeliste aller Kinder mit dem anon-Key lesbar.
drop policy if exists "teachers read freigaben" on public.mathe9_freigaben;
drop policy if exists "teachers read lernzeit" on public.mathe9_lernzeit;
drop policy if exists "teachers read unterricht" on public.mathe9_unterricht;

create policy "teachers read freigaben"
on public.mathe9_freigaben for select to authenticated
using (public.mathe9_ist_lehrkraft());

create policy "teachers read lernzeit"
on public.mathe9_lernzeit for select to authenticated
using (public.mathe9_ist_lehrkraft());

create policy "teachers read unterricht"
on public.mathe9_unterricht for select to authenticated
using (public.mathe9_ist_lehrkraft());

grant select on public.mathe9_freigaben to authenticated;
grant select on public.mathe9_lernzeit to authenticated;
grant select on public.mathe9_unterricht to authenticated;


-- ============================================================
-- V36 · Abschlussquiz am Ende einer Lerneinheit
--
-- Bis V35 lieferte die Anwendung Fortschritt, Lernzeit und Denkfehler —
-- alles Beobachtungen des Weges, keine Messung des Ergebnisses. Als
-- Grundlage fuer eine Note taugt das nicht: Wer lange braucht und viele
-- Tipps nutzt, kann am Ende trotzdem alles koennen, und umgekehrt.
--
-- Das Abschlussquiz schliesst die Luecke: fuenf Fragen ausschliesslich
-- zum Inhalt der eben bearbeiteten Einheit und des gewaehlten Pfades.
--
-- Zwei Festlegungen, beide mit Grund:
--
--   1. Gewertet wird der erste Lauf je Kind und EINHEIT, nicht je Tag.
--      Eine Einheit wird einmal erarbeitet; der Lauf unmittelbar danach
--      ist der aussagekraeftige. Wer sie in einer Woche wiederholt, uebt.
--
--   2. Der Lauf wird auch ausserhalb des Bewertungsmodus aufgezeichnet.
--      Eine Einheit, die zu Hause selbstaendig erarbeitet wird, ist der
--      Regelfall dieses Projekts und nicht die Ausnahme. Ob solche
--      Laeufe in die Note eingehen, entscheidet die Lehrkraft im
--      Dashboard (Schalter "nur Laeufe aus dem Unterricht") - nicht das
--      Geraet und nicht diese Datei. Festgehalten wird beides: das
--      Ergebnis und die Frage, ob es im Unterricht entstanden ist.
--
-- Gespeichert werden Zaehlwerte und die Kennungen der Denkfehler, keine
-- Antworttexte. Siehe DATENSCHUTZ.md.
-- ============================================================

-- Wonach wird dieses Kind bewertet? Die Entscheidung trifft die Lehrkraft
-- je Person, nicht die Anwendung fuer alle:
--
--   note         Der Durchschnitt der einzelnen Ergebnisse.
--   fortschritt  Die Entwicklung ueber die Zeit. Wer schwach anfaengt und
--                besser wird, soll dafuer nicht mit dem Mittelwert der
--                schwachen Anfaenge bezahlen.
alter table public.mathe9_students
  add column if not exists bewertungsart text not null default 'note';

do $bwa$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'mathe9_students_bewertungsart'
  ) then
    alter table public.mathe9_students
      add constraint mathe9_students_bewertungsart
      check (bewertungsart in ('note', 'fortschritt'));
  end if;
end;
$bwa$;


create table if not exists public.mathe9_quiz_ergebnisse (
  id bigint generated by default as identity primary key,

  student_id uuid not null
    references public.mathe9_students(id) on delete cascade,

  datum date not null default (now() at time zone 'Europe/Berlin')::date,

  -- Zu welcher Einheit? Kleingeschrieben wie ueberall sonst ("pz-08").
  unit text not null,
  -- Der Lernbereich, aus der Einheitenkennung abgeleitet ("pz"). Redundant,
  -- aber die Auswertung je Bereich ist die haeufigste Frage der Lehrkraft;
  -- ein like-Vergleich waere bei jedem Aufruf ein Tabellenscan.
  bereich text,
  pfad text,

  aufgaben smallint not null,
  richtig smallint not null,
  dauer_s integer not null default 0,

  -- Woran es lag: die IDs der getroffenen Fehlvorstellungen, bei
  -- erzeugten Fragen die Art ("quiz_merksatz", "quiz_fachwort").
  schwaechen text[] not null default array[]::text[],

  -- Lief zu diesem Zeitpunkt der Bewertungsmodus? Also: im Unterricht
  -- geschrieben oder zu Hause geuebt.
  pflicht boolean not null default false,

  -- Erster Lauf zu dieser Einheit - der, der zaehlt.
  gewertet boolean not null default false,

  erstellt_at timestamptz not null default now(),

  constraint mathe9_quiz_anzahl check (aufgaben between 1 and 20),
  constraint mathe9_quiz_richtig check (richtig between 0 and aufgaben),
  constraint mathe9_quiz_pfad check (pfad is null or pfad in ('A', 'B', 'C'))
);

alter table public.mathe9_quiz_ergebnisse enable row level security;

create index if not exists
  mathe9_quiz_person_idx
  on public.mathe9_quiz_ergebnisse (student_id, datum desc);

create index if not exists
  mathe9_quiz_einheit_idx
  on public.mathe9_quiz_ergebnisse (unit, datum desc);

create index if not exists
  mathe9_quiz_gewertet_idx
  on public.mathe9_quiz_ergebnisse (gewertet, datum desc)
  where gewertet;

-- Hoechstens ein gewerteter Lauf je Kind und Einheit. Die Regel steht als
-- Index in der Datenbank und nicht nur in der Funktion: Zwei Geraete, die
-- gleichzeitig melden, duerfen nicht zwei gewertete Laeufe erzeugen.
create unique index if not exists
  mathe9_quiz_ein_gewerteter_pro_einheit
  on public.mathe9_quiz_ergebnisse (student_id, unit)
  where gewertet;


-- ------------------------------------------------------------
-- Lehrkraftseite: Bewertungsart je Person festlegen
-- ------------------------------------------------------------
create or replace function public.mathe9_bewertungsart_setzen(
  p_student uuid,
  p_art text
)
returns text
language plpgsql
security definer
set search_path = public
as $fn$
declare
  gesetzt text;
begin
  if not public.mathe9_ist_lehrkraft() then
    raise exception 'Nur freigeschaltete Lehrkraefte duerfen die Bewertungsart aendern.'
      using errcode = '42501';
  end if;
  if p_art not in ('note', 'fortschritt') then
    raise exception 'Unbekannte Bewertungsart: %', p_art;
  end if;

  update public.mathe9_students
     set bewertungsart = p_art, updated_at = now()
   where id = p_student
  returning bewertungsart into gesetzt;

  if gesetzt is null then
    raise exception 'Unbekannte Person.';
  end if;
  return gesetzt;
end;
$fn$;

revoke all on function public.mathe9_bewertungsart_setzen(uuid, text) from public, anon;
grant execute on function public.mathe9_bewertungsart_setzen(uuid, text) to authenticated;


-- ------------------------------------------------------------
-- Quizergebnis melden  (Aufruf mit Schueler-Token)
-- ------------------------------------------------------------
create or replace function public.mathe9_quiz_melden(
  p_unit text,
  p_pfad text,
  p_aufgaben integer,
  p_richtig integer,
  p_dauer_s integer default 0,
  p_schwaechen text[] default array[]::text[]
)
returns table (gewertet boolean, quote numeric, pflicht boolean)
language plpgsql
security definer
set search_path = public
as $fn$
declare
  kind uuid;
  aktuell public.mathe9_unterricht%rowtype;
  ist_pflicht boolean;
  wird_gewertet boolean;
  n_aufgaben smallint;
  n_richtig smallint;
  einheit text;
  reihe text;
begin
  kind := public.mathe9_token_student();
  if kind is null then
    raise exception 'Kein gueltiges Schueler-Sitzungstoken.' using errcode = '42501';
  end if;

  einheit := nullif(lower(trim(coalesce(p_unit, ''))), '');
  if einheit is null then
    raise exception 'Ohne Einheit gibt es kein Quizergebnis.' using errcode = '22023';
  end if;
  reihe := nullif(split_part(einheit, '-', 1), '');

  -- Werte werden gedeckelt, nicht geglaubt. Ein Aufruf mit 500 richtigen
  -- von 5 Fragen ist kein Ergebnis, sondern ein Angriff.
  n_aufgaben := least(greatest(coalesce(p_aufgaben, 0), 1), 20);
  n_richtig := least(greatest(coalesce(p_richtig, 0), 0), n_aufgaben);

  select * into aktuell from public.mathe9_unterricht where id = 1;
  ist_pflicht := aktuell.modus = 'bewertung'
    and (aktuell.gilt_bis is null or aktuell.gilt_bis > now());

  -- Gewertet wird der erste Lauf zu dieser Einheit.
  wird_gewertet := not exists (
    select 1 from public.mathe9_quiz_ergebnisse q
    where q.student_id = kind
      and q.unit = einheit
      and q.gewertet
  );

  begin
    insert into public.mathe9_quiz_ergebnisse
      (student_id, unit, bereich, pfad, aufgaben, richtig, dauer_s,
       schwaechen, pflicht, gewertet)
    values
      (kind, einheit, reihe,
       nullif(upper(trim(coalesce(p_pfad, ''))), ''),
       n_aufgaben, n_richtig,
       least(greatest(coalesce(p_dauer_s, 0), 0), 3600),
       coalesce(p_schwaechen, array[]::text[]),
       ist_pflicht, wird_gewertet);
  exception when unique_violation then
    -- Zwei Geraete gleichzeitig. Der zweite Lauf wird als Uebung gefuehrt,
    -- nicht verworfen - er ist ja trotzdem passiert.
    wird_gewertet := false;
    insert into public.mathe9_quiz_ergebnisse
      (student_id, unit, bereich, pfad, aufgaben, richtig, dauer_s,
       schwaechen, pflicht, gewertet)
    values
      (kind, einheit, reihe,
       nullif(upper(trim(coalesce(p_pfad, ''))), ''),
       n_aufgaben, n_richtig,
       least(greatest(coalesce(p_dauer_s, 0), 0), 3600),
       coalesce(p_schwaechen, array[]::text[]),
       ist_pflicht, false);
  end;

  return query select
    wird_gewertet,
    round(n_richtig::numeric / n_aufgaben, 3),
    ist_pflicht;
end;
$fn$;

revoke all on function public.mathe9_quiz_melden(text, text, integer, integer, integer, text[]) from public;
grant execute on function public.mathe9_quiz_melden(text, text, integer, integer, integer, text[]) to anon, authenticated;


-- ------------------------------------------------------------
-- Bewertungsuebersicht je Kind
--
-- Zwei Wege zur Note, und die Wahl trifft die Lehrkraft je Kind:
--
--   Einzelnoten     Mittel aller gewerteten Laeufe. Das uebliche Verfahren.
--   Lernfortschritt Der Stand am Ende, zuzueglich der Verbesserung
--                   gegenueber dem Anfang. Fuer Kinder, bei denen der
--                   Mittelwert die Entwicklung verdeckt statt sie zu zeigen.
--
-- Gerechnet wird beides hier und nicht im Client: Eine Notenskala gehoert
-- an eine Stelle, sonst steht in einem halben Jahr in zwei Dateien eine
-- andere. Die Umrechnung folgt der Berliner Sekundarstufenskala.
--
-- p_nur_unterricht: Zaehlt nur, was im Bewertungsmodus geschrieben wurde.
-- Ob ein zu Hause bearbeitetes Quiz eine Note begruenden darf, ist eine
-- Frage der Fachkonferenz und keine der Datenbank - deshalb ein Schalter
-- und keine feste Regel.
-- ------------------------------------------------------------
create or replace function public.mathe9_quiz_uebersicht(
  p_klasse text default null,
  p_tage integer default 180,
  p_nur_unterricht boolean default false
)
returns table (
  student_id uuid,
  name text,
  klasse text,
  bewertungsart text,
  laeufe integer,
  einheiten integer,
  aufgaben integer,
  richtig integer,
  quote_gesamt numeric,
  quote_frueh numeric,
  quote_spaet numeric,
  punktwert numeric,
  note smallint,
  letzter_lauf date,
  schwache_einheiten text[]
)
language sql
stable
security definer
set search_path = public
as $fn$
  with fenster as (
    select q.*,
           row_number() over (partition by q.student_id order by q.datum, q.id) as lfd,
           count(*) over (partition by q.student_id) as gesamt
      from public.mathe9_quiz_ergebnisse q
     where q.gewertet
       and (not coalesce(p_nur_unterricht, false) or q.pflicht)
       and q.datum >= (now() - make_interval(days => greatest(coalesce(p_tage, 180), 1)))::date
  ),
  je_person as (
    select f.student_id,
           count(*)::integer as laeufe,
           count(distinct f.unit)::integer as einheiten,
           sum(f.aufgaben)::integer as aufgaben,
           sum(f.richtig)::integer as richtig,
           round(sum(f.richtig)::numeric / nullif(sum(f.aufgaben), 0), 3) as quote_gesamt,
           round(sum(f.richtig) filter (where f.lfd <= ceil(f.gesamt / 2.0))::numeric
                 / nullif(sum(f.aufgaben) filter (where f.lfd <= ceil(f.gesamt / 2.0)), 0), 3)
             as quote_frueh,
           round(sum(f.richtig) filter (where f.lfd > ceil(f.gesamt / 2.0))::numeric
                 / nullif(sum(f.aufgaben) filter (where f.lfd > ceil(f.gesamt / 2.0)), 0), 3)
             as quote_spaet,
           max(f.datum) as letzter_lauf,
           -- Nicht "63 Prozent", sondern welche Einheit nicht sass.
           (select array_agg(distinct g.unit)
              from fenster g
             where g.student_id = f.student_id
               and g.richtig::numeric / g.aufgaben < 0.6) as schwache_einheiten
      from fenster f
     group by f.student_id
  ),
  bewertet as (
    select s.id as student_id,
           s.display_name as name,
           s.class_code as klasse,
           s.bewertungsart,
           coalesce(p.laeufe, 0) as laeufe,
           coalesce(p.einheiten, 0) as einheiten,
           coalesce(p.aufgaben, 0) as aufgaben,
           coalesce(p.richtig, 0) as richtig,
           p.quote_gesamt,
           p.quote_frueh,
           p.quote_spaet,
           case
             when p.laeufe is null then null
             when s.bewertungsart = 'fortschritt' then
               least(1.0, coalesce(p.quote_spaet, p.quote_gesamt)
                          + greatest(0, coalesce(p.quote_spaet, 0) - coalesce(p.quote_frueh, 0)))
             else p.quote_gesamt
           end as punktwert,
           p.letzter_lauf,
           coalesce(p.schwache_einheiten, array[]::text[]) as schwache_einheiten
      from public.mathe9_students s
      left join je_person p on p.student_id = s.id
     where s.active
       and (p_klasse is null or s.class_code = p_klasse)
  )
  select b.student_id, b.name, b.klasse, b.bewertungsart,
         b.laeufe, b.einheiten, b.aufgaben, b.richtig,
         b.quote_gesamt, b.quote_frueh, b.quote_spaet,
         round(b.punktwert, 3),
         case
           when b.punktwert is null then null
           when b.punktwert >= 0.92 then 1
           when b.punktwert >= 0.81 then 2
           when b.punktwert >= 0.67 then 3
           when b.punktwert >= 0.50 then 4
           when b.punktwert >= 0.30 then 5
           else 6
         end::smallint,
         b.letzter_lauf,
         b.schwache_einheiten
    from bewertet b
   order by b.name;
$fn$;

revoke all on function public.mathe9_quiz_uebersicht(text, integer, boolean) from public, anon;
grant execute on function public.mathe9_quiz_uebersicht(text, integer, boolean) to authenticated;


-- ------------------------------------------------------------
-- Uebersicht je Einheit
--
-- Die Frage, die eine Bewertungstabelle nicht beantwortet: Lag es am
-- Kind oder an der Stunde? Wenn zweiundzwanzig von fuenfundzwanzig
-- Kindern in PZ-08 unter der Haelfte bleiben, war nicht die Klasse
-- schwach, sondern die Einheit unklar.
-- ------------------------------------------------------------
create or replace function public.mathe9_quiz_einheiten(
  p_klasse text default null,
  p_tage integer default 180,
  p_nur_unterricht boolean default false
)
returns table (
  unit text,
  bereich text,
  kinder integer,
  laeufe integer,
  quote numeric,
  unter_der_haelfte integer,
  haeufigste_schwaeche text
)
language sql
stable
security definer
set search_path = public
as $fn$
  with laeufe as (
    select q.*
      from public.mathe9_quiz_ergebnisse q
      join public.mathe9_students s on s.id = q.student_id
     where q.gewertet
       and s.active
       and (not coalesce(p_nur_unterricht, false) or q.pflicht)
       and (p_klasse is null or s.class_code = p_klasse)
       and q.datum >= (now() - make_interval(days => greatest(coalesce(p_tage, 180), 1)))::date
  )
  select l.unit,
         max(l.bereich) as bereich,
         count(distinct l.student_id)::integer as kinder,
         count(*)::integer as laeufe,
         round(sum(l.richtig)::numeric / nullif(sum(l.aufgaben), 0), 3) as quote,
         count(*) filter (where l.richtig::numeric / l.aufgaben < 0.5)::integer as unter_der_haelfte,
         (select oben.k from (
            select unnest(g.schwaechen) as k, count(*) as n
              from laeufe g
             where g.unit = l.unit
             group by 1
             order by n desc, k
             limit 1
          ) oben) as haeufigste_schwaeche
    from laeufe l
   group by l.unit
   order by quote nulls last, l.unit;
$fn$;

revoke all on function public.mathe9_quiz_einheiten(text, integer, boolean) from public, anon;
grant execute on function public.mathe9_quiz_einheiten(text, integer, boolean) to authenticated;


-- Die Schueler-App schreibt ausschliesslich ueber mathe9_quiz_melden().
-- Direkten Tabellenzugriff bekommt sie nicht - sonst waeren die
-- Ergebnisse der ganzen Klasse mit dem anon-Key lesbar.
drop policy if exists "teachers read quiz" on public.mathe9_quiz_ergebnisse;

create policy "teachers read quiz"
on public.mathe9_quiz_ergebnisse for select to authenticated
using (public.mathe9_ist_lehrkraft());

grant select on public.mathe9_quiz_ergebnisse to authenticated;


-- ============================================================
-- Loeschfristen planmaessig ausfuehren
--
-- mathe9_aufraeumen() allein loescht nichts — es muss aufgerufen werden.
-- Ist pg_cron im Projekt verfuegbar, richtet der folgende Block einen
-- woechentlichen Lauf ein (sonntags 03:17 UTC). Sonst bleibt der Aufruf
-- ein dokumentierter Handgriff, siehe DATENSCHUTZ.md.
-- ============================================================

do $plan$
begin
  if exists (select 1 from pg_available_extensions where name = 'pg_cron') then
    execute 'create extension if not exists pg_cron';

    perform cron.unschedule(jobid)
    from cron.job
    where jobname = 'mathe9-aufraeumen';

    perform cron.schedule(
      'mathe9-aufraeumen',
      '17 3 * * 0',
      'select public.mathe9_aufraeumen();'
    );

    raise notice 'pg_cron: woechentlicher Aufraeumlauf eingerichtet.';
  else
    raise notice 'pg_cron nicht verfuegbar — mathe9_aufraeumen() muss manuell oder extern geplant werden.';
  end if;
exception when others then
  raise notice 'pg_cron konnte nicht eingerichtet werden (%). Bitte manuell planen.', sqlerrm;
end;
$plan$;


commit;
