-- ============================================================
-- Mathe9
-- Freigabeliste, Tracking und langfristiger Lernfortschritt
--
-- Dieses Skript ist für eine erneute Ausführung vorbereitet.
-- Vorhandene Tabellen und Daten bleiben grundsätzlich erhalten.
--
-- Bei mehrfach vorhandenen Fortschrittszeilen für dieselbe
-- Kombination aus Schüler, Einheit und Lernpfad bleibt der
-- zuletzt aktualisierte Datensatz erhalten.
-- ============================================================

begin;


-- ============================================================
-- Erweiterungen
-- ============================================================

create extension if not exists pgcrypto;


-- ============================================================
-- Schüler-Freigabeliste
-- ============================================================

create table if not exists public.mathe9_students (
  id uuid
    primary key
    default gen_random_uuid(),

  login_name text
    not null,

  display_name text
    not null,

  class_code text
    not null,

  active boolean
    not null
    default true,

  created_at timestamptz
    not null
    default now(),

  updated_at timestamptz
    not null
    default now(),

  constraint mathe9_students_login_format
    check (
      login_name ~
      '^[^[:space:].]+\.[^[:space:].]+$'
    ),

  constraint mathe9_students_login_group_unique
    unique (
      login_name,
      class_code
    )
);


-- ============================================================
-- Einzelereignisse
-- ============================================================

create table if not exists public.mathe9_events (
  id bigint
    generated by default as identity
    primary key,

  event_type text
    not null,

  student_id uuid
    references public.mathe9_students(id)
    on delete set null,

  student text
    not null
    default 'anonym',

  device_id uuid
    not null,

  session_id uuid
    not null,

  class_code text,

  page text,

  unit text,

  path text,

  task text,

  payload jsonb
    not null
    default '{}'::jsonb,

  ts timestamptz
    not null
    default now()
);


-- ============================================================
-- Zusammengefasster Lernfortschritt
-- ============================================================

create table if not exists public.mathe9_progress (
  id bigint
    generated by default as identity
    primary key,

  student_id uuid
    references public.mathe9_students(id)
    on delete cascade,

  student text
    not null
    default 'anonym',

  device_id uuid
    not null,

  session_id uuid
    not null,

  class_code text,

  page text,

  unit text
    not null,

  path text
    not null
    default '',

  current_task text,

  completed_tasks integer
    not null
    default 0,

  total_tasks integer
    not null
    default 0,

  progress_percent integer
    not null
    default 0
    check (
      progress_percent
      between 0 and 100
    ),

  correct_count integer
    not null
    default 0,

  attempts_count integer
    not null
    default 0,

  status text
    not null
    default 'active',

  ts timestamptz
    not null
    default now(),

  updated_at timestamptz
    not null
    default now()
);


-- ============================================================
-- Migration bereits vorhandener Tabellen
-- ============================================================

alter table public.mathe9_events
  add column if not exists student_id uuid
  references public.mathe9_students(id)
  on delete set null;

alter table public.mathe9_progress
  add column if not exists student_id uuid
  references public.mathe9_students(id)
  on delete cascade;


-- Alte Eindeutigkeitsregeln entfernen, falls sie vorhanden sind.

alter table public.mathe9_progress
  drop constraint if exists
  mathe9_progress_device_id_session_id_unit_path_key;

alter table public.mathe9_progress
  drop constraint if exists
  mathe9_progress_device_unit_path_key;


-- ============================================================
-- Bestehende Werte normalisieren
--
-- Diese Anweisungen sind vor allem für ältere Tabellenstände
-- gedacht, in denen einzelne Felder noch NULL sein könnten.
-- ============================================================

update public.mathe9_progress
set
  path = coalesce(path, ''),
  completed_tasks = greatest(
    0,
    coalesce(completed_tasks, 0)
  ),
  total_tasks = greatest(
    0,
    coalesce(total_tasks, 0)
  ),
  progress_percent = least(
    100,
    greatest(
      0,
      coalesce(progress_percent, 0)
    )
  ),
  correct_count = greatest(
    0,
    coalesce(correct_count, 0)
  ),
  attempts_count = greatest(
    0,
    coalesce(attempts_count, 0)
  ),
  status = coalesce(
    nullif(trim(status), ''),
    'active'
  ),
  updated_at = coalesce(
    updated_at,
    ts,
    now()
  );


-- ============================================================
-- Vorhandene Fortschritts-Dubletten bereinigen
--
-- Eindeutig sein soll:
--
--   student_id + unit + path
--
-- Wenn dieselbe Kombination mehrfach vorkommt, bleibt:
--
--   1. der zuletzt aktualisierte Datensatz,
--   2. bei identischem Zeitpunkt der Datensatz mit der
--      höchsten ID.
--
-- Datensätze ohne student_id werden hier nicht verändert.
-- ============================================================

with ranked_progress as (
  select
    id,

    row_number() over (
      partition by
        student_id,
        unit,
        path

      order by
        updated_at desc nulls last,
        ts desc nulls last,
        id desc
    ) as duplicate_position

  from public.mathe9_progress

  where student_id is not null
)

delete from public.mathe9_progress as progress

using ranked_progress as ranked

where
  progress.id = ranked.id
  and ranked.duplicate_position > 1;


-- ============================================================
-- Eindeutiger Schlüssel für den Fortschritts-Upsert
--
-- Dieser Index entspricht exakt dem Tracker-Aufruf:
--
-- on_conflict=student_id,unit,path
-- ============================================================

drop index if exists
  public.mathe9_progress_student_unit_path_uidx;

create unique index
  mathe9_progress_student_unit_path_uidx

on public.mathe9_progress (
  student_id,
  unit,
  path
);


-- ============================================================
-- Zusätzliche Indizes
-- ============================================================

create index if not exists
  mathe9_events_ts_idx

on public.mathe9_events (
  ts desc
);


create index if not exists
  mathe9_events_student_idx

on public.mathe9_events (
  student_id,
  ts desc
);


create index if not exists
  mathe9_events_type_idx

on public.mathe9_events (
  event_type,
  ts desc
);


create index if not exists
  mathe9_progress_updated_idx

on public.mathe9_progress (
  updated_at desc
);


create index if not exists
  mathe9_students_class_idx

on public.mathe9_students (
  class_code,
  active,
  login_name
);


-- ============================================================
-- Login-Prüfung ohne Offenlegung der Schülerliste
-- ============================================================

create or replace function
  public.mathe9_validate_student_login(
    p_login_name text,
    p_class_code text
  )

returns table (
  student_id uuid,
  login_name text,
  display_name text,
  class_code text
)

language sql

security definer

set search_path = public

stable

as $$

  select
    student.id,
    student.login_name,
    student.display_name,
    student.class_code

  from public.mathe9_students as student

  where
    lower(student.login_name) =
      lower(trim(p_login_name))

    and student.class_code =
      trim(p_class_code)

    and student.active = true

  limit 1;

$$;


-- ============================================================
-- Rechte der Login-Funktion
-- ============================================================

revoke all
on function
  public.mathe9_validate_student_login(
    text,
    text
  )
from public;


grant execute
on function
  public.mathe9_validate_student_login(
    text,
    text
  )
to anon, authenticated;


-- ============================================================
-- Row Level Security aktivieren
-- ============================================================

alter table
  public.mathe9_students
enable row level security;


alter table
  public.mathe9_events
enable row level security;


alter table
  public.mathe9_progress
enable row level security;


-- ============================================================
-- Bestehende Policies entfernen
--
-- Dadurch kann das Skript erneut ausgeführt werden.
-- ============================================================

drop policy if exists
  "teachers read students"
on public.mathe9_students;


drop policy if exists
  "teachers insert students"
on public.mathe9_students;


drop policy if exists
  "teachers update students"
on public.mathe9_students;


drop policy if exists
  "teachers delete students"
on public.mathe9_students;


drop policy if exists
  "students insert events"
on public.mathe9_events;


drop policy if exists
  "students insert progress"
on public.mathe9_progress;


drop policy if exists
  "students update progress"
on public.mathe9_progress;


drop policy if exists
  "teachers read events"
on public.mathe9_events;


drop policy if exists
  "teachers read progress"
on public.mathe9_progress;


-- ============================================================
-- Freigabeliste nur für angemeldete Lehrkräfte
-- ============================================================

create policy
  "teachers read students"

on public.mathe9_students

for select

to authenticated

using (true);


create policy
  "teachers insert students"

on public.mathe9_students

for insert

to authenticated

with check (true);


create policy
  "teachers update students"

on public.mathe9_students

for update

to authenticated

using (true)

with check (true);


create policy
  "teachers delete students"

on public.mathe9_students

for delete

to authenticated

using (true);


-- ============================================================
-- Schüler-App
--
-- Die anonyme Anwendung darf Trackingdaten schreiben,
-- jedoch nicht die Schülerliste lesen.
-- ============================================================

create policy
  "students insert events"

on public.mathe9_events

for insert

to anon

with check (
  student_id is not null
);


create policy
  "students insert progress"

on public.mathe9_progress

for insert

to anon

with check (
  student_id is not null
);


create policy
  "students update progress"

on public.mathe9_progress

for update

to anon

using (
  student_id is not null
)

with check (
  student_id is not null
);


-- ============================================================
-- Dashboarddaten nur nach Lehrkraft-Login
-- ============================================================

create policy
  "teachers read events"

on public.mathe9_events

for select

to authenticated

using (true);


create policy
  "teachers read progress"

on public.mathe9_progress

for select

to authenticated

using (true);


-- ============================================================
-- Grundrechte
-- ============================================================

grant usage
on schema public
to anon, authenticated;


grant execute
on function
  public.mathe9_validate_student_login(
    text,
    text
  )
to anon, authenticated;


grant insert
on public.mathe9_events
to anon;


grant insert, update
on public.mathe9_progress
to anon;


grant select, insert, update, delete
on public.mathe9_students
to authenticated;


grant select
on
  public.mathe9_events,
  public.mathe9_progress
to authenticated;


grant usage, select
on all sequences in schema public
to anon, authenticated;


commit;
