create table if not exists public.mathe9_events (
  id bigint generated by default as identity primary key,
  event_type text not null,
  student text not null default 'anonym',
  device_id uuid not null,
  session_id uuid not null,
  class_code text,
  page text,
  unit text,
  path text,
  task text,
  payload jsonb not null default '{}'::jsonb,
  ts timestamptz not null default now()
);

create index if not exists mathe9_events_ts_idx
on public.mathe9_events(ts desc);

create index if not exists mathe9_events_device_idx
on public.mathe9_events(device_id, ts desc);

create index if not exists mathe9_events_type_idx
on public.mathe9_events(event_type, ts desc);


create table if not exists public.mathe9_progress (
  id bigint generated by default as identity primary key,
  student text not null default 'anonym',
  device_id uuid not null,
  session_id uuid not null,
  class_code text,
  page text,
  unit text not null,
  path text not null default '',
  current_task text,
  completed_tasks integer not null default 0,
  total_tasks integer not null default 0,
  progress_percent integer not null default 0
    check (progress_percent between 0 and 100),
  correct_count integer,
  attempts_count integer,
  status text not null default 'active',
  ts timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(device_id, session_id, unit, path)
);

create index if not exists mathe9_progress_updated_idx
on public.mathe9_progress(updated_at desc);


alter table public.mathe9_events enable row level security;
alter table public.mathe9_progress enable row level security;


drop policy if exists "student insert events"
on public.mathe9_events;

create policy "student insert events"
on public.mathe9_events
for insert
to anon
with check (true);


drop policy if exists "student insert progress"
on public.mathe9_progress;

create policy "student insert progress"
on public.mathe9_progress
for insert
to anon
with check (true);


drop policy if exists "student update progress"
on public.mathe9_progress;

create policy "student update progress"
on public.mathe9_progress
for update
to anon
using (true)
with check (true);


drop policy if exists "dashboard read events"
on public.mathe9_events;

create policy "dashboard read events"
on public.mathe9_events
for select
to anon
using (true);


drop policy if exists "dashboard read progress"
on public.mathe9_progress;

create policy "dashboard read progress"
on public.mathe9_progress
for select
to anon
using (true);


grant usage on schema public to anon;
grant insert, select on public.mathe9_events to anon;
grant insert, update, select on public.mathe9_progress to anon;
grant usage, select on all sequences in schema public to anon;
